name: Release

on:
  push:
    branches: main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  packages: write

env:
  NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install jq
        run: sudo apt-get install jq

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn

      - name: Get changesets status
        id: changeset-status
        run: |
          yarn changeset status --output status.json 2>/dev/null
          CHANGESETS_LENGTH=$(jq '.changesets | length' < status.json)
          HAS_CHANGES=$([ "$CHANGESETS_LENGTH" -gt 0 ] && echo true || echo false)

          [ $HAS_CHANGES = true ] && echo "Has changes" || echo "No changes found"
          echo "hasChanges=$HAS_CHANGES" >> $GITHUB_OUTPUT

          rm status.json

      - name: Test output
        run: echo ${{steps.changeset-status.outputs.hasChanges}}

      - name: Version packages
        if: ${{ false}}
        run: yarn release:version

      - name: Publish packages
        if: ${{ false}}
        run: yarn release:publish

      - name: Push changes to Repo
        if: ${{ false}}
        run: |
          git config user.name = release-bot
          git config email.email = relase@bot.com

          git push origin main
